/**
 * Problem Details class
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
  [key: string]: any;

  /**
   * A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when de-referenced, it provide human-readable documentation for the problem type.
   * @type {string}
   * @memberof ProblemDetails
   */
  type?: string | null;
  /**
   * A short, human-readable summary of the problem type.
   * @type {string}
   * @memberof ProblemDetails
   */
  title?: string | null;
  /**
   * The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   * @type {number}
   * @memberof ProblemDetails
   */
  status?: number | null;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   * @type {string}
   * @memberof ProblemDetails
   */
  detail?: string | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.It may or may not yield further information if de-referenced.
   * @type {string}
   * @memberof ProblemDetails
   */
  instance?: string | null;
  /**
   * Specifies the errors corresponding to the model properties, if any.
   * @type {{ [key: string]: string[]; }}
   * @memberof ProblemDetails
   */
  errors?: Record<string, string[]> | null;
}
